### ISSUE TITLE
開発環境をセットアップする

### ISSUE THREAD

**Issue by ramdos0207** [traP-jp/traO-Judge-frontend#4]
仮のページが1枚生えており、今すぐ開発可能な状態のリポジトリを用意する

**Comment by Pugma** [comment]
すでにVueとviteのセットアップ終わってます
一応確認してramdosくんの想定通りのところまで進んでたらcloseしてほしい！

**Comment by ramdos0207** [comment]
ごめん！何も見ずにissueを転記していました。ぱっと見良さそうです！
（traQにRSS購読チャンネル生やすとかしてもいいかも？）

**Comment by Pugma** [comment]
logの整備をやりました

**Comment by ramdos0207** [comment]
:tada:
