### ISSUE TITLE
ファイルの末尾の改行を強制したい

### ISSUE THREAD

**Issue by YuHima03** [traP-jp/traO-Judge-frontend#41]
ファイルの末尾に改行があったほうがいいようなので、ESLintで強制させるかPrettierでフォーマットできるようにしておきたい。

**Comment by mathsuky** [comment]
`.vue`はフォーマッターが効いててうまくいきそう？その他の拡張子のファイルを意図していますかね(`.ts`など)

**Comment by mathsuky** [comment]
`.ts`も効いていそうだな。どのようなことをイメージしていますか？

**Comment by ZOI-dayo** [comment]
僕がフォーマットかけずにpushしてたからそう思ったのかもしれない(ごめん)

**Comment by YuHima03** [comment]
`npm run lint` でファイルの末尾の改行を検証したり、`lint:fix` で自動的に修正してくれるのをイメージしています.

vscodeにPrettierとかを入れてる環境だと勝手に直してくれますが、それらが入っていない環境でも `lint:fix` で直せるようにした方が良いと思ってます.

**Comment by YuHima03** [comment]
あ、 `npm run format` で改行入れてくれてるかもしれない。

すみません Prettier の存在をすっかり忘れてました。

**Comment by mathsuky** [comment]
問題なさそうならcloseしてしまっても良いかも
