### ISSUE TITLE
ログイン画面

### ISSUE THREAD

**Issue by mathsuky** [traP-jp/traO-Judge-frontend#60]
https://www.figma.com/design/r4TYukz0TtWkyasBVUXWFc/DesignSystem%2Fv0?node-id=1537-1204&node-type=frame&t=EBZaFamVrbpAcArA-0
OAuthの部分は見た目だけで良い。

**Comment by kitsne241** [comment]
期日を書き忘れてました！ひとまず来週末（12/14）までにPRを出します

**Comment by kitsne241** [comment]
Google、GitHub、traQ などのアイコンはプロジェクトのどこかに保存されていますか？ない場合はどこに追加すればよいですか？

**Comment by mathsuky** [comment]
保存されていないはずなので，ルート以下に'sec/assets'を作成し，そこに追加していただければと思います。よろしくお願いします。

**Comment by YuHima03** [comment]
@kitsne241 取り掛かってくれてありがとう！！

僕から少し補足説明があるので確認してもらえると嬉しいです🙇‍♂

- Googleロゴの利用と「Googleでログイン」ボタンのについては <https://developers.google.com/identity/branding-guidelines?hl=ja> を参照してください。
- GitHubロゴの利用については <https://github.com/logos> を参照してください。

**Comment by kitsne241** [comment]
遅くなりすみません！とりあえず出来るだけ忠実に作りました
https://github.com/traP-jp/traO-Judge-frontend/tree/login-page
Tailwind CSS を初めて使ったので色々不出来な部分があると思います。遠慮なく指摘していただけると助かります

- Google のロゴに関しては[ガイドライン](https://developers.google.com/identity/branding-guidelines?hl=ja)がRobotoを用いて丸い形のボタンを作ること以外認めない？ようにも読めるので、実際どうなのかを伺いたいです
- traQ の白抜きでないバージョンのロゴを公式に配布している場所が見つからなかったので、とりあえずデザイン部分のSVGをそのまま拝借しました
- 若干文字が太い気がします。Noto Sans JP かつ 500 で合わせてあるはずなので不思議です

<img width="883" alt="スクリーンショット 2024-12-15 14 44 23" src="https://github.com/user-attachments/assets/4ce33d59-9e85-469c-9da2-4a7f3dc64a08" />

**Comment by kitsne241** [comment]
PRを出しました https://github.com/traP-jp/traO-Judge-frontend/pull/74
