### ISSUE TITLE
 問題提出コンポーネント

### ISSUE THREAD

**Issue by mathsuky** [traP-jp/traO-Judge-frontend#65]
https://www.figma.com/design/r4TYukz0TtWkyasBVUXWFc/DesignSystem%2Fv0?node-id=1499-748&node-type=frame&t=EBZaFamVrbpAcArA-0

**Comment by ZOI-dayo** [comment]
コード表示部分は`/problems/:id/submissions/:submissionId`などでも使うと思うので、
- コード表示用の簡易エディタコンポーネント (エディタ部分にはライブラリを使用)
- ↑に言語選択・提出ボタンを付けたコンポーネント (問題下部の提出欄、および提出画面で使う予定)

の2つを実装します
期限は12/15にします
